version: "3"

services:
  flask_app:
    image: peeps:${APP_VERSION}
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - mongo-express

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ~/mongodb:/data/db
    container_name: mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    container_name: mongo-express